バニラの設定を保存して呼び出すシステム
tukasa0001/TownOfHost pull request #1252
Opened 2023-02-05 14:50 UTC by Dekokiyo

- Mod導入時に他プレイヤーのゲームに参加した際にバニラ設定が上書きされるため、それの防止柵
- 保存形式はxml(改変可能)
- 今後プリセット機能や不適切な値があった場合に適切な処理をする対応を追加予定
- クソコード
- 画像の背景はAmongUsの素材、絵は自分で図形を組み合わせて描きました。

2023-02-05 23:09 UTC, tukasa0001 commented
わざわざxml形式にする意味はありますか?
ロード処理を見る限り、順番で識別していて、name属性に意味があるようには見えません。

2023-02-05 23:55 UTC, soukunsandesu commented on Modules/Settings/LoadSettings.cs
> +    public static IGameOptions CurrentOptions => GameOptionsManager.Instance.currentGameOptions;
GameOptionsManager.Instance.CurrentGameOptionsの方が良いです

2023-02-06 00:00 UTC, soukunsandesu commented on Modules/Settings/LoadSettings.cs
> +    public static List<BoolOptionNames> BoolSettingNames = new()
```
Enum.GetValues(typeof(BoolOptionNames)).Cast<BoolOptionNames>()
```
で取得出来るかと

2023-02-06 00:14 UTC, soukunsandesu commented on Resources/string.csv
> +"SettingsSaved","Settings were successfully saveed!","設定が正常に保存されました!","","","",""
saveed

2023-02-06 00:16 UTC, soukunsandesu commented on Modules/Settings/LoadSettings.cs
> +namespace TownOfHost.Modules;
TownOfHost.Moduels.Settingsに変えてください

2023-02-06 00:16 UTC, Dekokiyo commented
·xmlにする必要
外部ライブラリを使用しないので試用していますが、速度重視で行くととても遅いようなので別の形式に変更します

ソースに複数ご指摘を頂いているのでそちらも随時修正します

2023-02-06 00:16 UTC, soukunsandesu commented on Modules/Settings/SaveSettings.cs
> +namespace TownOfHost.Modules;
TownOfHost.Moduels.Settingsに変えてください

2023-02-06 00:17 UTC, soukunsandesu commented on Modules/Settings/SettingButtons.cs
> +namespace TownOfHost.Modules;
TownOfHost.Moduels.Settingsに変えてください

2023-02-06 00:17 UTC, soukunsandesu commented on Patches/GameManagerPatch.cs
> +            if (AmongUsClient.Instance.AmHost) Modules.SettingButtons.ButtonsVisible(true);
TownOfHost.Moduelsでusingしてほしいです

2023-02-06 00:19 UTC, soukunsandesu commented on Modules/Settings/SettingButtons.cs
> +        passiveLoadButton.OnClick.AddListener((System.Action)delegate
ここだけSuystem.Actionなのが気になります。
ここら辺はメソッド化した方がいいかもしれません

2023-02-06 00:19 UTC, soukunsandesu commented on Modules/Settings/SaveSettings.cs
> +        }
ここら辺はメソッド化した方がいいですね

2023-02-06 00:22 UTC, Dekokiyo commented on Modules/Settings/LoadSettings.cs
> +    public static IGameOptions CurrentOptions => GameOptionsManager.Instance.currentGameOptions;
修正します

2023-02-06 00:22 UTC, Dekokiyo commented on Modules/Settings/LoadSettings.cs
> +    public static List<BoolOptionNames> BoolSettingNames = new()
ありがとうございます

2023-02-06 00:23 UTC, Dekokiyo commented on Resources/string.csv
> +"SettingsSaved","Settings were successfully saveed!","設定が正常に保存されました!","","","",""
修正します

2023-02-06 00:23 UTC, Dekokiyo commented on Modules/Settings/LoadSettings.cs
> +namespace TownOfHost.Modules;
分かりました

2023-02-06 00:23 UTC, Dekokiyo commented on Modules/Settings/SaveSettings.cs
> +namespace TownOfHost.Modules;
分かりました

2023-02-06 00:24 UTC, Dekokiyo commented on Patches/GameManagerPatch.cs
> +            if (AmongUsClient.Instance.AmHost) Modules.SettingButtons.ButtonsVisible(true);
分かりました

2023-02-06 00:28 UTC, Dekokiyo commented on Modules/Settings/SettingButtons.cs
> +        passiveLoadButton.OnClick.AddListener((System.Action)delegate
うる覚えですがUnityActinonだと何らかの理由で出来なかった気がするのですがんなわけ無いので今日中に確認します

2023-02-06 00:59 UTC, soukunsandesu commented
Csvライブラリが元からあるのでcsvでいいかと。

2023-02-06 01:07 UTC, soukunsandesu commented on Modules/Settings/SettingButtons.cs
> +    public static SpriteRenderer loadRenderer;
フィールドはなるべく先頭大文字の方がいいですね

2023-02-06 01:12 UTC, soukunsandesu commented on Modules/Settings/SettingButtons.cs
> +    public static BoxCollider2D loadCollider2D;
BoxCollider2Dって使ってます？

2023-02-06 01:18 UTC, soukunsandesu commented on Modules/Settings/LoadSettings.cs
> +    public static List<BoolOptionNames> BoolSettingNames = new()
戻り値がArrayになるのでListからArrayに変えた方がいいです(foreachは配列で回す方が高速だし、わざわざToListしなくてもいいから)

2023-02-06 03:17 UTC, Dekokiyo commented on Modules/Settings/SettingButtons.cs
> +    public static BoxCollider2D loadCollider2D;
ボタンの判定に必要です

2023-02-06 04:38 UTC, soukunsandesu commented on Modules/Settings/LoadSettings.cs
> +        if (File.Exists(@$"./{SaveSettings.SETTINGS_FOLDER}/GameSettings.xml"))
否定にしてreturnした方がネストが浅くなって読みやすくなるんじゃないかと

2023-02-06 04:43 UTC, soukunsandesu commented on Modules/Settings/SaveSettings.cs
> +            new(){ Name = "VisualTasks", BoolValue = GameOptionsManager.Instance.currentGameOptions.GetBool(BoolOptionNames.VisualTasks) },
ここら辺が必要には思えませんね
上で作ったリストでforeachを下で回したらいいと思います

2023-02-06 04:46 UTC, soukunsandesu commented on Modules/Settings/LoadSettings.cs
> +            xml.Load(@$"./{SaveSettings.SETTINGS_FOLDER}/GameSettings.xml");
PathはTOH_DATAフォルダから派生させてほしいです

2023-02-06 05:03 UTC, soukunsandesu commented on Modules/Settings/LoadSettings.cs
> +        Logger.SendInGame(string.Format(Translator.GetString("SettingsLoaded")), false);
string.Formatって使ってます？

2023-02-06 05:14 UTC, Dekokiyo commented on Modules/Settings/LoadSettings.cs
> +        Logger.SendInGame(string.Format(Translator.GetString("SettingsLoaded")), false);
多分コピべしたのが残ってます

2023-02-06 06:52 UTC, Dekokiyo commented on Modules/Settings/SettingButtons.cs
> +        passiveLoadButton.OnClick.AddListener((System.Action)delegate
んなこと無いですね。ただのミスです

2023-02-06 07:12 UTC, soukunsandesu commented on Modules/Settings/LoadSettings.cs
> +    public static List<BoolOptionNames> BoolSettingNames = new()
全然戻り値Arrayじゃなかったです
IEnumerable<T>でした

2023-02-06 23:43 UTC, soukunsandesu commented on Modules/Settings/LoadSettings.cs
> +    public static List<BoolOptionNames> BoolSettingNames = new()
取得は一回だけでいいのでreadonlyにしてToArray()で配列に直すかToList()でリストに直すかしてほしいですね

2023-02-09 15:07 UTC, Dekokiyo commented on Modules/Settings/LoadSettings.cs
> +        {
要修正&かくれんぼのオプションを別に分ける

2023-02-11 12:56 UTC, tukasa0001 requested changes

2023-02-11 12:56 UTC, tukasa0001 commented on Modules/Settings/LoadSettings.cs
> +            Settings.Add(i, setting.Split(":")[1]);
保存処理を見る限り以下の形式で保存されているように見えますが、読み出し処理は順番主体の処理に見えます。
```
<設定名>:<設定値>
```
**設定名などを入れずに順番主体の処理にするか、設定名などを含めてそれを元に読み出すか、はっきりと決めてください。**

2023-03-02 08:06 UTC, closed without merging