Feature/HideCode_cfg
tukasa0001/TownOfHost pull request #187
Opened 2022-03-09 03:26 UTC by Palpunte-Soukun

- HideCodesの``Town Of Host``テキストとカラーをConfigファイルに格納

2022-03-09 04:21 UTC, shu-TownofHost approved these changes
動作確認済であれば問題ないと思います。
一応他の開発者の誰か1人から承認をもらってからマージしてください。

2022-03-09 04:35 UTC, yurinakira commented
質問)
初心者質問で申し訳ないのですが、
configに格納する理由(メリット)って何ですか？
modColorをそのまま利用するのと違いがあまりわかっていなくて。。。

2022-03-09 04:47 UTC, Palpunte-Soukun commented
> 質問) 初心者質問で申し訳ないのですが、 configに格納する理由(メリット)って何ですか？ modColorをそのまま利用するのと違いがあまりわかっていなくて。。。

ユーザーが自由に簡単にHideCodeの文字と色を変更できるというメリットがありますね

2022-03-09 05:11 UTC, Palpunte-Soukun commented
> 動作確認済であれば問題ないと思います。 一応他の開発者の誰か1人から承認をもらってからマージしてください。

大問題が起きてました((

2022-03-09 05:17 UTC, yurinakira commented
直接は関係ありませんが、
余分なusingをしているファイルがいくつか見受けられたので、合わせて削除お願いします。
using BepInEx.Configuration;

2022-03-09 05:53 UTC, yurinakira requested changes
このやり方(configいじって色と文字変えられますよー)はどこかに手順記載しないのでしょうか？

→もしするのであれば、Colorコードがでたらめな値(#11111111 等のオーバーフロー)にした場合文字が消える現象があったので、無効なカラーコードの場合はデフォルトの値にするように対策を打つ必要があると思います。

→しないのであれば、この機能追加した意味がユーザー目線ないよねってなるのでPR取り下げ?と思ってます。

2022-03-09 05:58 UTC, yurinakira commented
修正入れてたので、追加修正はもういいのですが、
不要な以下のusingのみ削除して欲しかったです。(v1.4→v1.5でコンフリクト増えると面倒なので。。。)
>using BepInEx.Configuration;

2022-03-09 06:29 UTC, Palpunte-Soukun commented
>

2022-03-09 06:34 UTC, Palpunte-Soukun commented
> Colorコードがでたらめな値(#11111111 等のオーバーフロー)にした場合文字が消える現象があったので、無効なカラーコードの場合はデフォルトの値にするように対策を打つ必要があると思います。

無効なカラーコードの検知の仕方がわからないです

2022-03-09 07:24 UTC, yurinakira commented
>無効なカラーコードの検知の仕方がわからないです(少し調べましたが、全くわからないです)

.valueで値取得して、Colorコードか判定してってやりかたにすればいいんじゃないかと思います。

これとか参考にすればいけませんか？
https://github.com/tukasa0001/TownOfHost/blob/v1.5/Patches%2FClientOptionsPatch.cs#L32

2022-03-09 07:40 UTC, mii-47 commented
つ ``ColorUtility.TryParseHtmlString()``
https://docs.unity3d.com/ja/current/ScriptReference/ColorUtility.TryParseHtmlString.html

2022-03-09 11:58 UTC, Palpunte-Soukun commented
@mii-47 ColorUtilityが存在しない。と言われるんですがなぜかわかりますか？

2022-03-09 12:00 UTC, Palpunte-Soukun commented
> > 無効なカラーコードの検知の仕方がわからないです(少し調べましたが、全くわからないです)
> 
> .valueで値取得して、Colorコードか判定してってやりかたにすればいいんじゃないかと思います。
> 
> これとか参考にすればいけませんか？ https://github.com/tukasa0001/TownOfHost/blob/v1.5/Patches%2FClientOptionsPatch.cs#L32

自分には全く思い浮かばなかったです

2022-03-09 12:01 UTC, mii-47 commented
@Palpunte-Soukun 
そのソースコード内で ``using UnityEngine`` されていますか？
フルネームは ``UnityEngine.ColorUtility.TryParseHtmlString``です。

2022-03-09 12:41 UTC, Palpunte-Soukun commented
> @Palpunte-Soukun そのソースコード内で `using UnityEngine` されていますか？ 

されています

2022-03-09 14:39 UTC, mii-47 commented
@Palpunte-Soukun 
今日空き瓶さんと私がUnityEngine内のクラスにアクセス出来ない問題かな...

[コレ](https://discord.com/channels/931559416413687848/932221425245368340/951071485873762334)を実施してみて``ColorUtility``が出てくるか確認してみてください。

2022-03-09 17:10 UTC, tanakanira0118 commented
ColorUtilityは実は以前使おうとしたのですが、コンパイルは通ってVSCode上ではエラーとなるのでやむなく自分でメソッド作りましたね
最悪どうしても使えなければGetRoleColorを参考にして自分でメソッド作ってください

2022-03-10 01:04 UTC, mii-47 commented
VSCodeで見ると参照できなくなった...
BepInEx/unhollowed の再生成で参照できるようになりました。

(そしてプルリクCloseしてしまう操作ミスしましたスミマセン)

2022-03-10 05:23 UTC, Palpunte-Soukun commented
@mii-47 解決しました！

2022-03-10 07:39 UTC, yurinakira commented on Patches/GameStartManagerPatch.cs
不要であればこのコメントは削除してください。

2022-03-10 07:42 UTC, yurinakira approved these changes
残：不要なコメントの削除

残以外の問題が見られないので承認

2022-03-10 08:41 UTC, merged