feature/Lighter
tukasa0001/TownOfHost pull request #231
Opened 2022-03-15 10:48 UTC by shu-TownofHost

タスクを完了させると視界が広がって、停電の影響を受けなくなるクルーメイトです。
テスト内容
・タスク完了時に視界が広がるか
・停電中のタスク完了時に視界が広がるか
・停電が明けてない状態での会議を挟んだ後に視界が広がっているか
・ホストで↑ができるか
・クライアントで↑ができるか

feature/PLighterとなっているのは前のライターのコードを参考にしつつ作ったので、同じ名前ではないほうがいいと思って

2022-03-15 12:53 UTC, Palpunte-Soukun requested changes

2022-03-15 12:55 UTC, Palpunte-Soukun commented on Patches/RecomputeTaskPatch.cs
> +            if(1 ==CustomRoles.Lighter.getCount()) {
2人以上いると動きません

2022-03-15 12:58 UTC, shu-TownofHost commented on Patches/RecomputeTaskPatch.cs
> +            if(1 ==CustomRoles.Lighter.getCount()) {
了解です

2022-03-15 14:06 UTC, yurinakira commented on Patches/RecomputeTaskPatch.cs
> +            if(1 ==CustomRoles.Lighter.getCount()) {
0人でも動きません。。。というか、条件ちゃいますよ....

ライター人数 > 0

2022-03-15 14:08 UTC, shu-TownofHost commented on Patches/RecomputeTaskPatch.cs
> +            if(1 ==CustomRoles.Lighter.getCount()) {
LighterCount > 0ってやつがリファクタリングで使えなくなっちゃってよくわかんなくなってしまったんです
なんでライター人数について考える必要性がアリ

2022-03-15 14:10 UTC, Palpunte-Soukun commented on Patches/RecomputeTaskPatch.cs
> +            if(1 ==CustomRoles.Lighter.getCount()) {
if(CustomRoles.Lighter.getCount() > 0) {
で行けました

2022-03-15 14:15 UTC, shu-TownofHost commented on Patches/RecomputeTaskPatch.cs
> +            if(1 ==CustomRoles.Lighter.getCount()) {
修正完了

2022-03-15 14:54 UTC, Palpunte-Soukun approved these changes

2022-03-16 07:02 UTC, shu-TownofHost commented on Resources/string.csv
>  MayorInfoLong,(Crewmates):\nCan have multiple votes for a meeting and put them all together into one person or skip. (with settings),(クルーメイト陣営):\n会議の票を複数持ち、まとめて一人または\nスキップに入れることができる。(設定有)
"のとこですかね？
消してみて、チャットが表示されなかったので必要です。

2022-03-16 15:23 UTC, Palpunte-Soukun commented
@shu-TownofHost 多分もうマージしてOKだと思いますよ

2022-03-16 23:15 UTC, shu-TownofHost commented
ほか問題見当たらなさそうなので、マージします。
問題見つけたら修正ブランチ切ってPR出します

2022-03-16 23:15 UTC, merged