Refact/DeathReason
tukasa0001/TownOfHost pull request #345
Opened 2022-04-09 09:33 UTC by Palpunte-Soukun

DeathReasonをConditionに変えてAliveもConditionに入れました。すべて動作確認済みです

2022-04-10 23:10 UTC, kou-hetare commented
出来れば変更に至る理由も記載してほしいです。

2022-04-11 07:27 UTC, Palpunte-Soukun commented
> 出来れば変更に至る理由も記載してほしいです。

Aliveだけ別だったのが気になったからです

2022-04-11 11:21 UTC, yurinakira commented
deathReasons から Conditionに変えた理由はありますか？
conditionsはgoogle翻訳で"条件"って出るんで、適切ではないかと
![image](https://user-images.githubusercontent.com/84663668/162729440-ac62a2fe-1691-4518-b4b1-40466f461ea5.png)

2022-04-11 15:26 UTC, tanakanira0118 commented
deathReasonsのままでも特に問題ない気がします

2022-04-11 15:26 UTC, tanakanira0118 commented on Patches/onGameStartedPatch.cs
> +            PlayerState.conditions = new Dictionary<byte, PlayerState.Condition>();
ここで再度初期化しているのはなぜですか？

2022-04-11 15:34 UTC, yurinakira commented
Stateだけだと何かわからないので、
tanakaさんと同じでdeathReasons のままでも良いかと思ってます。
もし変えたいのであれば player"生死系の英単語"Statesとかにした方が良いです。

2022-04-11 15:35 UTC, Palpunte-Soukun commented on Patches/onGameStartedPatch.cs
> +            PlayerState.conditions = new Dictionary<byte, PlayerState.Condition>();
別で初期化してましたっけ？

2022-04-11 15:36 UTC, tanakanira0118 requested changes
Thank you for the pull request.
We will be moving the folder tree, so please limit your request to changing the contents of the file.

2022-04-11 15:37 UTC, Palpunte-Soukun commented
Aliveだけ別なのが気になるだけなので変える必要がないというのならcloseしていただいても問題ありません。

2022-04-11 15:38 UTC, tanakanira0118 commented on Patches/onGameStartedPatch.cs
> +            PlayerState.conditions = new Dictionary<byte, PlayerState.Condition>();
同ファイル13行目で初期化がされています。

2022-04-11 15:39 UTC, Palpunte-Soukun commented on Patches/onGameStartedPatch.cs
> +            PlayerState.conditions = new Dictionary<byte, PlayerState.Condition>();
本当ですね。削除します

2022-04-11 15:40 UTC, tanakanira0118 approved these changes

2022-04-11 15:40 UTC, closed without merging